sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    browser->>server: {content: "single page app does not reload the whole page", date: "2019-05-25T15:15:59.905Z"}
    server-->>browser: HTTP status code 201
    deactivate server
