POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "My Blog2",
    "author": "Myself again",
    "url": "https://www.example.com",
    "likes": "12"
}
#
GET http://localhost:3003/api/blogs